
environment:
  access_token:
    secure: oyWN0U3twXyCpgzZpTmMNFJw0ejkR5VUCZta3+ytgX2QTvwHyPLRmR/Esu1wGeEL

image: Ubuntu1804  # образ для сборки

stack: node 16  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install --force  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint # скрипт тестирования
  
deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose